# Generated by Django 4.1.5 on 2023-01-14 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_db', '0003_rename_name_employee_navn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='qualification',
        ),
    ]
