# Generated by Django 4.1.5 on 2023-01-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_db', '0004_remove_employee_dob_remove_employee_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Navn',
            new_name='Name',
        ),
    ]
