# Generated by Django 4.1.5 on 2023-01-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_db', '0005_rename_navn_employee_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Eftermiddag',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Gruppe',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Morgen',
            new_name='middleName',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Ferie',
            new_name='phoneNo',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Alder',
            new_name='salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Empcode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='qualification',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
